[package]
name = "genesis-compute"
version = "0.1.0"
edition = "2021"

[features]
default = ["titan", "cpp"]
titan = ["genesis-core/titan"]
wgpu = ["dep:wgpu"]
cpp = []
cuda = []

[build-dependencies]
cc = "1.0"

[dependencies]
log = { workspace = true }
rand = { workspace = true }
rayon = "1.8"
thiserror = { workspace = true }
genesis-core = { path = "../genesis-core" }
wgpu = { workspace = true, optional = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
bincode = { workspace = true }
