[package]
name = "genesis-compute"
version = "0.1.0"
edition = "2021"

[features]
default = ["titan"]
titan = ["genesis-core/titan"]
wgpu = ["dep:wgpu"]

[dependencies]
log = { workspace = true }
rand = { workspace = true }
genesis-core = { path = "../genesis-core" }
wgpu = { workspace = true, optional = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
